id: P5BFAD774
initial_creation_type: ocr
source_metadata:
  volumes:
    808e7927171f47da92717c8e4c6ce692:
      base_file: v062.txt
      image_group_id: I1PD95907
      title: བདེན་པ་གཉིས་རྣམ་པར་འབྱེད་པའི་འགྲེལ་པ།
      total_pages: 1557
      volume_number: 62
